# Generated by Django 5.1.2 on 2024-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
