# Generated by Django 5.1.2 on 2024-10-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_students_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='gender',
            new_name='section',
        ),
    ]
