# Generated by Django 5.1.2 on 2024-10-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_gender_students_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studentid',
            field=models.IntegerField(unique=True),
        ),
    ]
